---
dist: bionic
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - libsystemd-dev
language: perl
perl:
  - blead
  - dev
  - '5.30'
  - '5.28'
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
    - perl: dev
  fast_finish: 1
  include:
    - env: COVERAGE=1
      perl: '5.30'
env:
  global:
    - NO_EDIT_CHANGES=1
    - RELEASE_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules --debug
